### ISSUE TITLE
crash on iOS 17

### ISSUE THREAD

**Issue by Duckmolemore** [aws-amplify/amplify-ui-swift-liveness#68]
Hi,
I built an app with Amplify 2.14.1 and AmplifyUILiveness 1.1.0.
I have noticed two types of crashes occurring sporadically on iOS 17.

Issue 1:
Description:

Crash Information: Fatal Exception: NSGenericException
*** -[AVCaptureSession startRunning] startRunning may not be called between calls to beginConfiguration and commitConfiguration
Crash Location: LivenessCaptureSession - Line 43
(DispatchQueue.global().async {
captureSession.startRunning()
})

Issue 2:
Description:

Crash Information: Fatal Exception: NSInternalInconsistencyException
*** -[AVAssetWriterInputPixelBufferAdaptor appendPixelBuffer:withPresentationTime:] Must start a session (using -[AVAssetWriter startSessionAtSourceTime:]) before appending pixel buffers
Crash Location: VideoChunker.swift - Line 71
pixelBufferAdaptor.append(
rotated,
withPresentationTime: presentationTime
)

**Comment by phantumcode** [comment]
@Duckmolemore Thanks for submitting. your issue, can you provide additional details to help reproduce the issue?  Is the crash occurring only on iOS 17?  is the crash occurring on all a specific device?  What are the steps to reproduce the issue?

**Comment by Duckmolemore** [comment]
> @Duckmolemore Thanks for submitting. your issue, can you provide additional details to help reproduce the issue? Is the crash occurring only on iOS 17? is the crash occurring on all a specific device? What are the steps to reproduce the issue?

The crashes only occur on iOS 17 and above, and they are not dependent on the device model. I haven't identified any specific steps to consistently reproduce the crashes

**Comment by donglyu** [comment]
We have encountered the same two issues, exactly. Using version information: Amplify 2.22.0 and AmplifyUILiveness 1.1.4

I am providing two Xcode xccrashpoint files on our end, to see if they might be helpful.
[xccrashpoint.zip](https://github.com/aws-amplify/amplify-ui-swift-liveness/files/13455571/xccrashpoint.zip)

**Comment by donglyu** [comment]
@phantumcode Okay, we will attempt to upgrade in the next version, as the new version 1.2.1 was released just before we submitted the new app version for review. Yesterday, we upgraded the version for testing and found that liveness verification consistently fails on iOS 17 devices (results return false). We tried with different individuals, and it failed dozens of times, so we did not upgrade the SDK in yesterday's new version.

**Comment by phantumcode** [comment]
@donglyu Can you provide details on the failure? the liveness check completes but the liveness results return false? What is your backend service or lambda logic for returning results of true/false?

**Comment by phantumcode** [comment]
@donglyu the latest version has been tested on iOS 17.1.1 repeated without any issues.  I'm not able to reproduce the issue you're reporting.

**Comment by yogeshelevn** [comment]
Hi @donglyu , I'm encountering the same issue while attempting to perform a face liveness check on an iPhone 13 running iOS 17.1.2. I've verified against the latest version 1.2.1. For your reference, I've included both a video file and the Xcode logs related to this problem.
https://drive.google.com/file/d/19H8R2FboUAW8apzbeKY4Oy0iP-VHCgwQ/view?usp=sharing
[xcode logs.pdf](https://github.com/aws-amplify/amplify-ui-swift-liveness/files/13646496/xcode.logs.pdf)

**Comment by yogeshelevn** [comment]
@phantumcode Yes, crash occurs when I attempt to restart the liveness feature after closing the previous session without using the visible 'close'  CTA in the face liveness.

**Comment by yogeshelevn** [comment]
@phantumcode Yes, This is flutter app. At the moment, I haven't set up TestFlight. So I can't share test .ipa build with you. So do let know me how can help you more on this ?

**Comment by phantumcode** [comment]
@yogeshelevn Can you provide a sample app source code and I can build and debug how you're integrating the component in a way that lets you dismiss without using the CTA?  I can update it to point to my backend service and auth

**Comment by yogeshelevn** [comment]
@phantumcode Sure, will share it soon.

**Comment by yogeshelevn** [comment]
@phantumcode  please check the raw same code.you will have to configure aws amplify, you will need to pass sessionId in main.dart file. sessionId you can Create using your own seutp. do let me know if you are facing any issue ? https://github.com/yogeshelevn/aws_sample_app

**Comment by phantumcode** [comment]
@yogeshelevn Note also that you can prevent the user from swiping away the liveness UI and use the CTA button instead by disabling modal presentation.  For example, in the sample code provided:

```swift
faceLivenessController.sessionId = sessionId
faceLivenessController.flutterResult = result
faceLivenessController.modalPresentationStyle = .fullScreen
controller.present(faceLivenessController, animated: true, completion: nil)
```

**Comment by yogeshelevn** [comment]
@phantumcode The issue has indeed been resolved, and now the face verification is working perfectly. Although I didn't test your bug fixes branch, I implemented your suggestion. Thank you for all your effort.

faceLivenessController.modalPresentationStyle = .fullScreen

**Comment by yogeshelevn** [comment]
<img width="1440" alt="Screenshot 2024-01-02 at 18 21 29" src="https://github.com/aws-amplify/amplify-ui-swift-liveness/assets/152858842/7f112ebd-dced-42d9-a21f-12941931c267">
@phantumcode  I am not able to download this package
https://github.com/aws-amplify/amplify-ui-swift-liveness/tree/fix/AVCaptureSession_race_condition . sharing Screenshot please check.

**Comment by phantumcode** [comment]
@yogeshelevn I'm able to add the package/branch without any issues:

<img width="800" alt="image" src="https://github.com/aws-amplify/amplify-ui-swift-liveness/assets/103537251/05f2fa5e-34b0-4fbb-84a7-6438afb9c15f">

<img width="800" alt="image" src="https://github.com/aws-amplify/amplify-ui-swift-liveness/assets/103537251/ada420aa-378c-4a97-925a-462dc307d50d">

**Comment by yogeshelevn** [comment]
@phantumcode I was able to install the fix branch code in my project. I did not faced issue related to AVCaptureSession. But I want to pointing out another issue that is like face liveness verification process is somehow broken experience is not up to mark. please check why this is happening. I am attaching video for your reference. Thanks
https://drive.google.com/file/d/1RbunrENqUqGcI2UxTLTqvp-nV-POOMzU/view?usp=sharing

**Comment by phantumcode** [comment]
@yogeshelevn I'm not able to reproduce the "broken experience" issue seen in the video.  Does the "broken experience" stil exist if you revert back to the main branch? Have you checked what the error is? Is it a service error? What is the error exception and code?  Why is the verification image rotated 90 degrees?

**Comment by yogeshelevn** [comment]
@phantumcode The face liveness check is functioning correctly from the main branch. I've shared the logs which I am getting from fix branch. Please check them to verify.
video :- https://drive.google.com/file/d/1M7dx-4cesRssgvoKPIyFTUpemY8v8Mvo/view?usp=sharing
Logs :-
`session id is 424473b5-16e0-447d-8520-b0c36aa847f7
2024-01-03T23:18:50+0530 info CognitoIdentityClient : [Logging] Request: POST https:443 
 Path: / 
 Content-Type: application/x-amz-json-1.1, 
X-Amz-Target: AWSCognitoIdentityService.GetId, 
Host: cognito-identity.ap-south-1.amazonaws.com, 
User-Agent: aws-sdk-swift/1.0 ua/2.0 api/cognito_identity#1.0 os/ios#17.1.2 lang/swift#5.9 cfg/retry-mode#legacy, 
Content-Length: 80 
 nil
2024-01-03T23:18:50+0530 info SerialExecutor : [Logging] Creating connection pool for cognito-identity.ap-south-1.amazonaws.com with max connections: 50
2024-01-03T23:18:50+0530 info CRTClientEngine : [Logging] Connection was acquired to: Optional("https://cognito-identity.ap-south-1.amazonaws.com/")
2024-01-03T23:18:50+0530 info CRTClientEngine : [Logging] Using HTTP/1.1 connection
2024-01-03T23:18:50+0530 info HttpContent : [Logging] read 80 bytes from data
2024-01-03T23:18:50+0530 info CRTClientEngine : [Logging] Main headers received
2024-01-03T23:18:50+0530 info CRTClientEngine : [Logging] Body chunk received
2024-01-03T23:18:50+0530 info CRTClientEngine : [Logging] Request/response completed
2024-01-03T23:18:50+0530 info CognitoIdentityClient : [Logging] Request: POST https:443 
 Path: / 
 Content-Type: application/x-amz-json-1.1, 
User-Agent: aws-sdk-swift/1.0 ua/2.0 api/cognito_identity#1.0 os/ios#17.1.2 lang/swift#5.9 cfg/retry-mode#legacy, 
Host: cognito-identity.ap-south-1.amazonaws.com, 
X-Amz-Target: AWSCognitoIdentityService.GetCredentialsForIdentity, 
Content-Length: 76 
 nil
2024-01-03T23:18:50+0530 info SerialExecutor : [Logging] Creating connection pool for cognito-identity.ap-south-1.amazonaws.com with max connections: 50
2024-01-03T23:18:50+0530 info CRTClientEngine : [Logging] Connection was acquired to: Optional("https://cognito-identity.ap-south-1.amazonaws.com/")
2024-01-03T23:18:50+0530 info CRTClientEngine : [Logging] Using HTTP/1.1 connection
2024-01-03T23:18:50+0530 info HttpContent : [Logging] read 76 bytes from data
error in connection_block_invoke_2: Connection invalid
2024-01-03T23:18:50+0530 info CRTClientEngine : [Logging] Main headers received
2024-01-03T23:18:50+0530 info CRTClientEngine : [Logging] Body chunk received
2024-01-03T23:18:50+0530 info CRTClientEngine : [Logging] Request/response completed
Liveness error: FaceLivenessDetectionError(code: 2, message: "Session timed out. Did not receive final response from server within time limit.", recoverySuggestion: "Try again.")
Liveness error: FaceLivenessDetectionError(code: 2, message: "Session timed out. Did not receive final response from server within time limit.", recoverySuggestion: "Try again.")
session id is cbc7ade2-8dda-4cbd-a95e-06a5b4aecca6
Liveness error: FaceLivenessDetectionError(code: 2, message: "Session timed out. Did not receive final response from server within time limit.", recoverySuggestion: "Try again.")
Liveness error: FaceLivenessDetectionError(code: 2, message: "Session timed out. Did not receive final response from server within time limit.", recoverySuggestion: "Try again.")
session id is c9acfc8b-ebdf-43a7-a38e-8a43ee8c3ee1
Liveness error: FaceLivenessDetectionError(code: 2, message: "Session timed out. Did not receive final response from server within time limit.", recoverySuggestion: "Try again.")
Liveness error: FaceLivenessDetectionError(code: 2, message: "Session timed out. Did not receive final response from server within time limit.", recoverySuggestion: "Try again.")`

**Comment by phantumcode** [comment]
@yogeshelevn The session is timing out and expiring after 10 seconds
```
Liveness error: FaceLivenessDetectionError(code: 2, message: "Session timed out. Did not receive final response from server within time limit.", recoverySuggestion: "Try again.")
```
Please make sure you've fit the face in the oval and starting the liveness check with the 10 seconds window.  I've noticed that the flutter app is very slow and memory-intensive compared to a native iOS app as well.  I'm not familiar with flutter, are their performance optimization that you look into as well?

**Comment by phantumcode** [comment]
@yogeshelevn Are you experiencing the issue on multiple devices? Are you able to test the same scenario with flutter and a native app?

**Comment by yogeshelevn** [comment]
@phantumcode  As you suggested, I tried to test it out fix branch code in iPhone 11 (16.3.1). I am experiencing the same broken experience. I tried to cover my face in oval shape only but every time I am getting "Session timed out. Did not receive final response from server within time limit.", recoverySuggestion: "Try again. ". Although everything is working fine in released main branch on the same device only. I am sharing videos for your reference. please check I highly doubt that there are some unwanted changes in fix branch code which is eventually broking user experience.
main branch :- https://drive.google.com/file/d/1EnUXd2gikoc-Tv2KDDcFRhI_N75xFl5W/view?usp=sharing
fix branch :- https://drive.google.com/file/d/1jsMwKohp4YFRwAlVSNxYWg6-3bOKJa6f/view?usp=sharing

**Comment by phantumcode** [comment]
@yogeshelevn The session timed out is expected based on the video recording.  You did not fit your face in the oval within the required time frame; try moving your face back farther to reset and then move your face closer to fit the oval.

The created session id has a expiration time as well as the time the oval is displayed.  What is the time difference between when the session id is first created and when the face fit oval is displayed and when the face is fit correctly in the oval?  If the face is fit in the oval when the "Hold still" instruction is displayed, then the session will eventually times out.  If your face is too close within the oval then you'll need to move your face back further to reset and then fit your face in the oval so that the "Hold still" instruction is displayed

**Comment by yogeshelevn** [comment]
@yogeshelevn time difference between session id created and face fit oval displayed is almost 2 second approx. and I am saying I am almost trying to fit my face my face in oval shape only but after 10 seconds I got error. I was able to see *Hold Still* instruction 2 times only out of more than 10 attempts and successfully completed verification for those 2 attempts. can you please confirm it is working fine for native iOS app ? for flutter app fix branch code is not working properly that I am sure. Although 1.2.1 version working fine.

Uploading RPReplay_Final1704388625.MP4…

**Comment by phantumcode** [comment]
@yogeshelevn I was able to reproduce the issue when running in a Flutter sample app.  Thanks for the feedback and your patience.  I'll keep troubleshooting the issue.

**Comment by yogeshelevn** [comment]
@phantumcode  Thanks for the confirmation. I wanted to highlight one point that this feature is very important for our product success and Your swift action for solving this issue would be greatly appreciated.

**Comment by phantumcode** [comment]
@yogeshelevn Please re-test the branch again https://github.com/aws-amplify/amplify-ui-swift-liveness/tree/fix/AVCaptureSession_race_condition

**Comment by yogeshelevn** [comment]
@phantumcode I retest the fix branch and Right now, face liveness is working properly. I confirm that your latest fix resolved all the issues.

**Comment by phantumcode** [comment]
Fix released in version [1.2.2](https://github.com/aws-amplify/amplify-ui-swift-liveness/releases/tag/1.2.2)

**Comment by ntnmrndn** [comment]
@phantumcode I still see this crash despite updating:
<img width="2032" alt="Screenshot 2024-01-15 at 13 08 10" src="https://github.com/aws-amplify/amplify-ui-swift-liveness/assets/1104823/17dac450-934b-43e0-88b2-d44d53dfb91e">

**Comment by phantumcode** [comment]
@ntnmrndn That screenshot looks to have outdated code.  Please make sure to clear your SPM cache and get the latest released version 1.2.2 and retry.
